#!/usr/bin/env python3
"""Generates mapsrc/ai_test_grunt.map — a minimal room with a monster_human_grunt,
for exercising the Hybrid AI Core's Phase A debug output (ai_hybrid_debug 1)
without loading a full campaign map.

GoldSrc/VHLT .map brush planes need an INWARD-pointing normal per face (verified
against a decompiled retail map, ~/hltools/decompiled/of0a0.map — its world-bound
brush uses this convention, not the "outward normal" convention some other map
formats use). This generator computes each face's 3 defining points, checks the
resulting normal sign with a cross product, and only emits points verified to
produce the correct inward normal, instead of hand-deriving them (which is easy
to get backwards).

Usage: python3 gen_ai_test_grunt.py > ai_test_grunt.map
"""
import numpy as np

B = 1000000  # huge coordinate; hlcsg's CSG stage clips each face down to the
             # brush's real, finite extent by intersecting with the other faces.


def cross(p0, p1, p2):
    p0, p1, p2 = np.array(p0, float), np.array(p1, float), np.array(p2, float)
    return np.cross(p1 - p0, p2 - p0)


def face_points(axis, value, sign):
    other = [a for a in range(3) if a != axis]
    a1, a2 = other

    def pt(v_axis, v1, v2):
        p = [0, 0, 0]
        p[axis] = v_axis
        p[a1] = v1
        p[a2] = v2
        return tuple(p)

    p0 = pt(value, B, B)
    p1 = pt(value, -B, B)
    p2 = pt(value, B, -B)
    n = cross(p0, p1, p2)
    n = n / np.linalg.norm(n)
    target = [0, 0, 0]
    target[axis] = sign
    if np.allclose(n, target, atol=1e-6):
        return p0, p1, p2
    p1, p2 = p2, p1
    n2 = cross(p0, p1, p2)
    n2 = n2 / np.linalg.norm(n2)
    assert np.allclose(n2, target, atol=1e-6), (axis, value, sign, n, n2)
    return p0, p1, p2


def box_faces(x0, x1, y0, y1, z0, z1):
    # (points, uaxis, vaxis) per face. The U/V basis must span the face's
    # plane (i.e. be perpendicular to its normal) or hlrad crashes with
    # "Malformed face normal" - so each axis-normal gets its own UV pair
    # instead of reusing one fixed pair for every face.
    return [
        (face_points(0, x0, +1), (0, 1, 0), (0, 0, -1)),  # X-normal: UV in Y/Z
        (face_points(0, x1, -1), (0, 1, 0), (0, 0, -1)),
        (face_points(1, y0, +1), (1, 0, 0), (0, 0, -1)),  # Y-normal: UV in X/Z
        (face_points(1, y1, -1), (1, 0, 0), (0, 0, -1)),
        (face_points(2, z0, +1), (1, 0, 0), (0, -1, 0)),  # Z-normal: UV in X/Y
        (face_points(2, z1, -1), (1, 0, 0), (0, -1, 0)),
    ]


def fmt_pt(p):
    return "( %d %d %d )" % tuple(int(round(c)) for c in p)


def fmt_axis(a):
    return "[ %d %d %d 0 ]" % a


def brush_text(x0, x1, y0, y1, z0, z1, texture="babtech6", label=""):
    lines = [f"// {label}"] if label else []
    for (p0, p1, p2), uaxis, vaxis in box_faces(x0, x1, y0, y1, z0, z1):
        lines.append(f"{fmt_pt(p0)} {fmt_pt(p1)} {fmt_pt(p2)} {texture} "
                      f"{fmt_axis(uaxis)} {fmt_axis(vaxis)} 0 1 1")
    return "{\n" + "\n".join(lines) + "\n}"


def main():
    brushes = [
        brush_text(-192, 192, -192, 192, -32, 0, label="floor"),
        brush_text(-192, 192, -192, 192, 288, 320, label="ceiling"),
        brush_text(-192, 192, 160, 192, 0, 288, label="wall north (+Y)"),
        brush_text(-192, 192, -192, -160, 0, 288, label="wall south (-Y)"),
        brush_text(160, 192, -192, 192, 0, 288, label="wall east (+X)"),
        brush_text(-192, -160, -192, 192, 0, 288, label="wall west (-X)"),
    ]

    print("// ai_test_grunt.map -- GENERATED by gen_ai_test_grunt.py, do not hand-edit.")
    print("// Minimal test room with a monster_human_grunt for Hybrid AI Core Phase A")
    print("// debug-output verification (ai_hybrid_debug 1). Rebuild with:")
    print("//   python3 mapsrc/gen_ai_test_grunt.py > mapsrc/ai_test_grunt.map")
    print("{")
    print('"classname" "worldspawn"')
    print('"mapversion" "220"')
    # Only needed at compile time (textures get embedded via hlcsg
    # -nowadtextures) - adjust this path if compiling on a different machine.
    print('"wad" "/home/masterbee/hltools/compile/halflife.wad"')
    print('"message" "AI Test - Grunt"')
    for b in brushes:
        print(b)
    print("}")
    print('{\n"classname" "info_player_start"\n"origin" "-100 0 16"\n"angles" "0 0 0"\n}')
    print('{\n"classname" "light"\n"origin" "0 0 250"\n"_light" "255 255 255 300"\n}')
    print('{\n"classname" "light"\n"origin" "100 0 250"\n"_light" "255 255 255 300"\n}')
    print('{\n"classname" "monster_human_grunt"\n"origin" "100 0 16"\n'
          '"angles" "0 180 0"\n"weapons" "3"\n}')


if __name__ == "__main__":
    main()
